# Generated by Django 2.2.10 on 2020-07-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myusers',
            table='users',
        ),
    ]
